# Generated by Django 3.1.7 on 2021-04-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_product_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/sliders/')),
                ('name', models.CharField(max_length=100, null=True)),
                ('tagline', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
