# Generated by Django 3.1.7 on 2021-04-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_sliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='active',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
